title: Geocoding & Web Mapping with Python
remote_theme: ubc-library-rc/rc-workshop-template
footer_content: "<a href=\"https://github.com/ubc-library-rc/Geocoding-Web-Mapping-with-Python/\">View in GitHub</a>"
